import React, { useState } from 'react';
import { 
  Bell, 
  ShieldAlert, 
  AlertTriangle, 
  Clock, 
  ChevronRight, 
  Radio, 
  Database,
  ExternalLink,
  CheckCircle2,
  History,
  Check,
  ShieldCheck
} from 'lucide-react';
import { isAlertActive } from '../../services/insightSupabase';

export function InsightAlertPanel({ 
  alerts = [], 
  allAlerts = [],
  onSelectAlert,
  onApproveAlert,
  onResolveAlert 
}) {
  const [viewFilter, setViewFilter] = useState('ACTIVE'); // 'ACTIVE' | 'ALL'
  const [processingAlertId, setProcessingAlertId] = useState(null);

  const displayAlerts = viewFilter === 'ACTIVE' 
    ? alerts 
    : (allAlerts.length > 0 ? allAlerts : alerts);

  const activeCount = alerts.length;
  const totalCount = allAlerts.length > 0 ? allAlerts.length : alerts.length;

  const handleQuickApprove = async (e, alertId) => {
    e.stopPropagation();
    if (!onApproveAlert) return;
    setProcessingAlertId(alertId);
    try {
      await onApproveAlert(alertId);
    } catch (err) {
      console.error('Quick approve error:', err);
    } finally {
      setProcessingAlertId(null);
    }
  };

  return (
    <div className="p-5 rounded-2xl bg-white dark:bg-slate-900/90 border border-slate-200 dark:border-slate-800 shadow-xs dark:shadow-lg dark:shadow-black/20 space-y-4">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 dark:border-slate-800/80 pb-3">
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-xl bg-purple-50 dark:bg-purple-950/80 border border-purple-200 dark:border-purple-800/60 text-purple-600 dark:text-purple-400">
            <Bell size={16} />
          </div>
          <div>
            <h3 className="text-xs font-bold uppercase font-mono tracking-wider text-slate-800 dark:text-slate-200">
              Live Security Threat Feed ({activeCount})
            </h3>
            <p className="text-[11px] text-slate-500 dark:text-slate-400 font-sans">
              Streamed from Supabase alerts table • Only active unapproved threats shown in active view
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2.5 flex-wrap">
          {/* Active vs Audit History Switcher */}
          <div className="flex items-center bg-slate-100 dark:bg-slate-950 p-1 rounded-xl border border-slate-200 dark:border-slate-800 text-[10px] font-mono">
            <button
              onClick={() => setViewFilter('ACTIVE')}
              className={`px-2.5 py-1 rounded-lg transition-all cursor-pointer ${
                viewFilter === 'ACTIVE'
                  ? 'bg-white dark:bg-rose-950/90 text-rose-700 dark:text-rose-300 border border-slate-200 dark:border-rose-800 font-bold shadow-xs'
                  : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
              }`}
            >
              Active Threats ({activeCount})
            </button>
            <button
              onClick={() => setViewFilter('ALL')}
              className={`px-2.5 py-1 rounded-lg transition-all cursor-pointer flex items-center gap-1 ${
                viewFilter === 'ALL'
                  ? 'bg-white dark:bg-purple-950 text-purple-700 dark:text-purple-300 border border-slate-200 dark:border-purple-800 font-bold shadow-xs'
                  : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
              }`}
            >
              <History size={10} />
              <span>Audit History ({totalCount})</span>
            </button>
          </div>

          <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-[10px] font-mono bg-purple-50 dark:bg-purple-950/80 text-purple-700 dark:text-purple-300 border border-purple-200 dark:border-purple-800">
            <Radio size={10} className="animate-pulse text-purple-600 dark:text-purple-400" />
            <span>REALTIME SUPABASE</span>
          </span>
        </div>
      </div>

      {/* Alerts List */}
      <div className="space-y-2.5 max-h-[460px] overflow-y-auto pr-1">
        {displayAlerts.length === 0 ? (
          <div className="p-8 text-center text-slate-500 font-mono text-xs space-y-2">
            <p className="text-slate-700 dark:text-slate-400 font-bold">
              {viewFilter === 'ACTIVE' ? 'All clear — No active threats pending review' : 'No alerts recorded in Supabase'}
            </p>
            <p className="text-[11px] text-slate-500 dark:text-slate-600">
              {viewFilter === 'ACTIVE' 
                ? 'All threats have been approved or resolved by the SOC analyst. Check Audit History for historical logs.' 
                : 'Alerts generated by workflow or detection will appear here in real-time.'}
            </p>
          </div>
        ) : (
          displayAlerts.map((alt) => {
            const isCritical = alt.severity === 'CRITICAL' || alt.risk_score >= 85 || alt.alert_type === 'CRITICAL';
            const isHigh = alt.severity === 'HIGH' || alt.risk_score >= 70;
            const statusStr = String(alt.status || 'NEW').toLowerCase().trim();
            const isApproved = statusStr === 'approved';
            const isResolved = statusStr === 'resolved';
            const isCurrentlyActive = isAlertActive(statusStr);
            const isProcessing = processingAlertId === alt.id;

            return (
              <div
                key={alt.id}
                onClick={() => onSelectAlert && onSelectAlert(alt)}
                className={`p-3.5 rounded-xl border transition-all cursor-pointer flex flex-col sm:flex-row sm:items-center justify-between gap-3 group ${
                  isApproved || isResolved
                    ? 'bg-slate-50/60 dark:bg-slate-950/60 border-slate-200 dark:border-slate-800/80 opacity-80 hover:opacity-100 hover:border-slate-300 dark:hover:border-slate-700'
                    : isCritical 
                    ? 'bg-rose-50/60 dark:bg-rose-950/20 border-rose-300 dark:border-rose-700/80 hover:border-rose-400 dark:hover:border-rose-500 hover:bg-rose-50 dark:hover:bg-rose-950/30 shadow-xs dark:shadow-md dark:shadow-rose-950/30 ring-1 ring-rose-400/30 dark:ring-rose-600/30' 
                    : isHigh
                    ? 'bg-orange-50/60 dark:bg-orange-950/20 border-orange-300 dark:border-orange-800/80 hover:border-orange-400 dark:hover:border-orange-600 hover:bg-orange-50 dark:hover:bg-orange-950/30'
                    : 'bg-slate-50 dark:bg-slate-950/80 border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700'
                }`}
              >
                {/* Left side: Severity badge, event text & employee */}
                <div className="flex items-start gap-3">
                  <div className={`p-2 rounded-xl shrink-0 mt-0.5 ${
                    isApproved 
                      ? 'bg-emerald-50 dark:bg-emerald-950 border border-emerald-200 dark:border-emerald-800 text-emerald-700 dark:text-emerald-400'
                      : isResolved
                      ? 'bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 text-blue-700 dark:text-blue-400'
                      : isCritical 
                      ? 'bg-rose-50 dark:bg-rose-950 border border-rose-200 dark:border-rose-700 text-rose-600 dark:text-rose-400 animate-pulse' 
                      : isHigh
                      ? 'bg-orange-50 dark:bg-orange-950 border border-orange-200 dark:border-orange-700 text-orange-600 dark:text-orange-400'
                      : 'bg-slate-100 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-cyan-700 dark:text-cyan-400'
                  }`}>
                    {isApproved ? <ShieldCheck size={16} /> : <ShieldAlert size={16} />}
                  </div>

                  <div className="space-y-1">
                    <div className="flex items-center gap-2 flex-wrap font-mono text-xs">
                      {/* Alert Type / Severity */}
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold border ${
                        isCritical 
                          ? 'bg-rose-50 dark:bg-rose-950 text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-700' 
                          : isHigh
                          ? 'bg-orange-50 dark:bg-orange-950 text-orange-700 dark:text-orange-300 border-orange-200 dark:border-orange-700'
                          : 'bg-emerald-50 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-700'
                      }`}>
                        {alt.alert_type || alt.severity}
                      </span>

                      {/* Employee Name */}
                      <span className="font-bold text-slate-900 dark:text-white">
                        {alt.employee_name}
                      </span>

                      {/* Employee Code */}
                      <span className="text-cyan-700 dark:text-cyan-300 px-1.5 py-0.2 rounded bg-slate-100 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-[10px]">
                        {alt.employee_code}
                      </span>

                      {/* Alert Status Badge */}
                      <span className={`text-[10px] font-mono px-2 py-0.5 rounded border ${
                        isApproved 
                          ? 'bg-emerald-50 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800 font-bold'
                          : isResolved
                          ? 'bg-blue-50 dark:bg-blue-950 text-blue-700 dark:text-blue-300 border-blue-200 dark:border-blue-800'
                          : 'bg-slate-100 dark:bg-slate-900 text-slate-600 dark:text-slate-400 border-slate-200 dark:border-slate-800'
                      }`}>
                        {String(alt.status || 'NEW').toUpperCase()}
                      </span>
                    </div>

                    {/* Alert Message */}
                    <p className="text-xs text-slate-700 dark:text-slate-300 font-sans line-clamp-2">
                      {alt.message}
                    </p>

                    {/* Alert ID & Timestamp */}
                    <div className="text-[10px] text-slate-500 font-mono flex items-center gap-2">
                      <span>ID: {alt.id}</span>
                      <span>•</span>
                      <span>{alt.created_at ? new Date(alt.created_at).toLocaleString() : 'Recent'}</span>
                    </div>
                  </div>
                </div>

                {/* Right side: Score & Action button */}
                <div className="flex sm:flex-col items-end justify-between sm:justify-center gap-2 shrink-0 border-t sm:border-t-0 pt-2 sm:pt-0 border-slate-100 dark:border-slate-800/80">
                  <div className="text-right">
                    <span className="text-[10px] text-slate-500 font-mono block">RISK SCORE</span>
                    <span className={`text-base font-black font-mono ${
                      isCritical ? 'text-rose-600 dark:text-rose-400' : isHigh ? 'text-orange-600 dark:text-orange-400' : 'text-emerald-600 dark:text-emerald-400'
                    }`}>
                      {alt.risk_score}
                      <span className="text-[10px] text-slate-500 font-normal">/100</span>
                    </span>
                  </div>

                  <div className="flex items-center gap-2">
                    {/* Quick Approve button if active */}
                    {isCurrentlyActive && onApproveAlert && (
                      <button
                        onClick={(e) => handleQuickApprove(e, alt.id)}
                        disabled={isProcessing}
                        className="px-2.5 py-1 bg-emerald-50 hover:bg-emerald-100 dark:bg-emerald-950/80 dark:hover:bg-emerald-900 text-emerald-700 dark:text-emerald-300 border border-emerald-300 dark:border-emerald-700 hover:border-emerald-500 rounded-lg text-[10px] font-mono font-bold flex items-center gap-1 transition-all cursor-pointer shadow-xs disabled:opacity-50"
                        title="Approve threat in Supabase and dismiss from Active Threats"
                      >
                        <Check size={11} />
                        <span>{isProcessing ? 'Saving...' : 'Approve'}</span>
                      </button>
                    )}

                    <div className="flex items-center gap-1 text-[11px] font-mono text-cyan-600 dark:text-cyan-400 group-hover:text-cyan-700 dark:group-hover:text-cyan-300">
                      <span>Inspect</span>
                      <ChevronRight size={13} className="group-hover:translate-x-0.5 transition-transform" />
                    </div>
                  </div>
                </div>

              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
